spring:
  datasource:
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yanfang.woc.entity